# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Thing

# Model Form Field configuration
form: $/bedard/vuetober/models/thing/fields.yaml

# Model Class name
modelClass: Bedard\Vuetober\Models\Thing

# Default redirect location
defaultRedirect: bedard/vuetober/things

# Create page
create:
    title: Create Thing
    redirect: bedard/vuetober/things/update/:id
    redirectClose: bedard/vuetober/things

# Update page
update:
    title: Edit Thing
    redirect: bedard/vuetober/things
    redirectClose: bedard/vuetober/things

# Preview page
preview:
    title: Preview Thing
